In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.6.0+cpu


### **Introduction to Tensors**

#### **Creating tensors**

In [2]:
# Scalar (names always in lowecase)
scalar = torch.tensor(7)
print(f'Scalar: {scalar}, Type: {type(scalar)}')

Scalar: 7, Type: <class 'torch.Tensor'>


In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as Python int
number = scalar.item()
print(f'Number: {number}, Type: {type(number)}')

Number: 7, Type: <class 'int'>


In [6]:
# Vector (names always in lowecase)
vector = torch.tensor([7,7])
print(f'Vector: {vector}, Type: {type(vector)}')

Vector: tensor([7, 7]), Type: <class 'torch.Tensor'>


In [7]:
vector.ndim # It returns 1 (it count's the number of square brackets)

1

In [8]:
vector.shape # It return the dimension of the tensor

torch.Size([2])

In [9]:
# MATRIX (names always in uppercase)
MATRIX = torch.tensor([[7,8], [9,10]]) # Always squared matrix
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
print(f'{MATRIX[0]}')
print(f'{MATRIX[1]}')

tensor([7, 8])
tensor([ 9, 10])


In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor (names always in uppercase)
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
print(f'{TENSOR[0]}\n')
print(f'{TENSOR[0][1]}\n')
print(f'{TENSOR[0][1][2]}\n')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([4, 5, 6])

6



#### **Random Tensors**

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2616, 0.0718, 0.4426, 0.6719],
        [0.2056, 0.8968, 0.1899, 0.7006],
        [0.3234, 0.9761, 0.9700, 0.3346]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### **Zeros and Ones**

In [20]:
# Create a tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
print(f'{ones.dtype}')
print(f'{zero.dtype}')

torch.float32
torch.float32


#### **Creating a range of tensors and tensors-like**

In [23]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
range_tensor = torch.arange(start=0, end=1000, step=77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten) # Created a zero tensor with the same shape as one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### **Tensor datatypes**

**Note:** tensors datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Leaning:
1. Tensors not right datatype (to get datatype from a tensor, can use 'tensor.dtype')
2. Tensors not right shape (to get shape from a tensor, can use 'tensor.shape')
3. Tensors not on right device (to get the device from a tensor, can use 'tensor.device')

In [26]:
# float32 tensor
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
print(f'{float32_tensor}')
print(f'{float32_tensor.dtype}') # The default datatype in PyTorch is float32 (even if it's specified as None)

tensor([3., 6., 9.])
torch.float32


In [27]:
# float16 tensor
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(f'{float16_tensor}')
print(f'{float16_tensor.dtype}')

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [28]:
tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16, # What datatype is the tensor
                               device=None, # None set by defualt, other options: cpu/cuda
                               requires_grad=False # If you want PyTorch to track the gradients of a tensor
                               )
print(f'{tensor}')
print(f'{tensor.dtype}')

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [29]:
float16_tensor * float32_tensor # Error! (Even if it seems to work, see 1.)

tensor([ 9., 36., 81.])

#### **Getting information from tensors (tensor attributes)**

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5876, 0.5755, 0.8025, 0.8033],
        [0.6612, 0.8404, 0.2368, 0.4751],
        [0.0309, 0.1725, 0.2240, 0.7227]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}') # Or some_tensor.size()
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.5876, 0.5755, 0.8025, 0.8033],
        [0.6612, 0.8404, 0.2368, 0.4751],
        [0.0309, 0.1725, 0.2240, 0.7227]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#### **Manipulating tensors (tensor operations)**

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication (dot product)

In [32]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# Try out PyTorch in-built functions
print(f'Addition: {torch.add(tensor, 10)}')
print(f'Multiplication: {torch.mul(tensor, 10)}')
print(f'Subtraction: {torch.sub(tensor, 10)}')

Addition: tensor([11, 12, 13])
Multiplication: tensor([10, 20, 30])
Subtraction: tensor([-9, -8, -7])


#### **Matrix multiplication**

Two main ways of perfoming multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [36]:
# Element wise multiplication
print(tensor, '*', tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [37]:
print(tensor, "@", tensor, "=", tensor @ tensor)

tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
%%time
value = 0.0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14.)
CPU times: total: 0 ns
Wall time: 2.99 ms


In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

#### **One of the most common errors in deep learning: shape errors**

There are two main rules that perfoming matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], 
                         [3, 4], 
                         [5, 6]])

tensor_B = torch.tensor([[7, 10], 
                         [8, 11], 
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul, but only for tensors with exactly 2 dimensions
# This is an error!

In [42]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issuers, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [43]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [44]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [45]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [46]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#### **Finding the min, max, mean, sum, etc (tensor aggregation)**

In [47]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [49]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
# Error: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
# torch.mean(x), x.mean()

# Cast the tensor form int64 to float32 and then do the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [51]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

#### **Finding the positional min and max**

In [52]:
y = torch.arange(1, 100, 10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the position in the tensor that has the minimum value with the function argmin()
# -> returns the index position of the target tensor where the minimum occurs
y.argmin(), torch.argmin(y)

(tensor(0), tensor(0))

In [54]:
y[y.argmin()]

tensor(1)

In [55]:
# Find the position in the tensor that has the maximum value with the function argmax()
# -> returns the index position of the target tensor where the maximum occurs
y.argmax(), torch.argmax(y)

(tensor(9), tensor(9))

In [56]:
y[y.argmax()]

tensor(91)

#### **Reshaping, stacking, squeezing and unsqueezing tensors**

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keeè the same memory as the original tensor
* Stacking - combina multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [85]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 5., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [70]:
x_reshaped = x.reshape(3, 3) # Keep in mind the new shape must be correlated to the original shape (3*3 = 9, 1*9 = 9*1 = 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [86]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[0][0] = 50
z, x

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [95]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x]) # Defualt dim=0: stack vertically
x_stacked, x_stacked.shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([4, 9]))

In [94]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # dim=1 stack orizontally
x_stacked, x_stacked.shape

(tensor([[50., 50., 50., 50.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]),
 torch.Size([9, 4]))

In [103]:
h_stack = torch.hstack([x, x, x, x])
h_stack, h_stack.shape

(tensor([50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 50.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  9., 50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 50.,
          2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([36]))

In [105]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b)), torch.hstack((a,b)).shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

In [97]:
v_stack = torch.vstack([x, x, x, x])
v_stack, v_stack.shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([4, 9]))

In [106]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b)), torch.vstack((a,b)).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]),
 torch.Size([6, 1]))

In [135]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 5., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [138]:
x_reshaped.squeeze() # It removed all single dimensions

tensor([5., 2., 3., 5., 5., 6., 7., 8., 9.])

In [143]:
y = torch.zeros(1, 1, 3)
print(y, y.shape)
print(y.squeeze(), y.squeeze().shape)

tensor([[[0., 0., 0.]]]) torch.Size([1, 1, 3])
tensor([0., 0., 0.]) torch.Size([3])


In [159]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {y}")
print(f"Previous shape: {y.shape}")

# Add an extra dimension with unsqueeze
y_unsqueezed = y.unsqueeze(dim=0)
print(f"\nPrevious target: {y_unsqueezed}")
print(f"Previous shape: {y_unsqueezed.shape}")

Previous target: tensor([[[0., 0., 0.]]])
Previous shape: torch.Size([1, 1, 3])

Previous target: tensor([[[[0., 0., 0.]]]])
Previous shape: torch.Size([1, 1, 1, 3])


In [165]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2 and 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#### **Indexing (selecting data from tensors)**

Indexing with PyTorch is similar to indexing with NumPy

In [171]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [173]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [176]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [177]:
# Let's index on the most inner backet (last dimension)
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [184]:
# You can use ":" to select all elements of a target dimension
x[0][0][:], x[0, 0, :]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [186]:
# Get the values of 0th and last dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [187]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [188]:
# Get index 0 of 0th and 1st dimension and all vales of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [195]:
print(f"Index on x to return 9: {x[0][2][2]}")
print(f"Index on x to return 3, 6, 9: {x[:, :, 2]}")

Index on x to return 9: 9
Index on x to return 3, 6, 9: tensor([[3, 6, 9]])


### **PyTorch tensors & NumPy**

Numpy is a popular scientific Python numerica computing library.

And because of this, PyTorch has functionality to interact with it.

* NumPy -> PyTorch tensor. Then use `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy. Then use `torch.Tensor.numpy()`

In [204]:
# NumPy array to tensor
arrayNumpy = np.arange(1.0, 8.0)
tensorTorch = torch.from_numpy(arrayNumpy)
arrayNumpy, arrayNumpy.dtype, tensorTorch, tensorTorch.dtype
# Note that the tensors' default dtype in PyTorch is float32 while in NumPy is float64. 
# And the conversion keep the previous dtype.
# Be aware of that.

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [208]:
arrayNumpy = np.arange(1.0, 8.0)
tensorTorch = torch.from_numpy(arrayNumpy).type(torch.float32)
arrayNumpy, arrayNumpy.dtype, tensorTorch, tensorTorch.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [210]:
# Change the value of arrayNumpy, what will this do to tensorTorch?
arrayNumpy = arrayNumpy + 1
arrayNumpy, tensorTorch # Does not change the values of tensorTorch.

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [213]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpyTensor = tensor.numpy()
tensor, numpyTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [214]:
# Change the tensor, what happes to numpyTensor?
tensor = tensor + 1
tensor, numpyTensor # Does not change the values of numpyTensor.

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### **Recproducibility (trying to take random out of random)**

In [215]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0424, 0.4438, 0.2787, 0.5899],
        [0.3564, 0.7229, 0.5780, 0.3145],
        [0.4069, 0.3928, 0.3886, 0.1520]])
tensor([[0.2533, 0.5673, 0.9251, 0.2475],
        [0.5700, 0.5927, 0.9230, 0.8895],
        [0.9984, 0.7619, 0.8871, 0.6747]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [217]:
# Let's make some random but reproductible tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # It only works for one block of code (the next one) if you using a notebook
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # It only works for one block of code (the next one) if you using a notebook
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### **Running tensors and PyTorch objects on the GPUs (and making faster computations)**

In [ ]:
# Go to GoogleColab's toolbar -> Runtime -> Change runtime type -> set a GPU e run this command to see which GPU you have
!nvidia-smi

In [218]:
# Check for GPU access with PyTorch (by defualt in GoogleColab)
torch.cuda.is_available()

False

#### **Agnostic code**

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.

In [219]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [221]:
# Count the number of devices
torch.cuda.device_count()

0

#### **Putting tensors (and models) on the GPU**

The reason we want out tensors/models on the GPU is because using GPU results in faster computations.

In [262]:
# Create a tensor
tensor = torch.tensor([1, 2, 3]) # By default the tensors will be computed by the CPU 

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [263]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [264]:
# Move tensor back to the CPU
# If tensors is on GPU, can't transform it to NumPy!
tensor_on_gpu.numpy()
# To fix the GPU tensor with NumPy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

### **Exercises**

1. Create a random tensor with shape (7, 7)

In [368]:
random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

2. Perform a matrix multiplication on the tensor between the tensor in the exercise 1 with another random tensor with shape (1, 7) 

In [369]:
random_tensor_A = torch.rand(1, 7)
# Inner dimension must match! -> use the transpose - Output shape: the outer dimension: (7,1) 
output = torch.matmul(random_tensor, random_tensor_A.T)
output, output.shape

(tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]),
 torch.Size([7, 1]))

3. Set the random seed to 0 and do exercises 2 & 3 over again.

In [370]:
# Ex. 1
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7,7)
print(random_tensor, random_tensor.shape)

# Ex. 2
random_tensor_A = torch.rand(1, 7)
output = torch.matmul(random_tensor, random_tensor_A.T)
print(output, output.shape)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) torch.Size([7, 7])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? If there is, set the GPU random seed to 1234.

In [371]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [372]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)
device, tensor_A_gpu, tensor_B_gpu


('cpu',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

6. Perform a matrix multiplication on the tensors you created in 6

In [373]:
output = torch.matmul(tensor_A_gpu, tensor_B_gpu.T)
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

7. Find the maximum and minimum values of the output of the exercise 6

In [374]:
torch.max(output), torch.min(output)

(tensor(0.5617), tensor(0.3647))

8. Find the maximum and minimum index values of the output of the exercise 6.

In [375]:
torch.argmax(output), torch.argmin(output)

(tensor(3), tensor(0))

9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [376]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(1, 1, 1, 10)
tensor_B = torch.squeeze(tensor_A)
print(f"Tensor_A: {tensor_A}, with shape: {tensor_A.shape}")
print(f"\nTensor_B: {tensor_B}, with shape: {tensor_B.shape}")

Tensor_A: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), with shape: torch.Size([1, 1, 1, 10])

Tensor_B: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), with shape: torch.Size([10])
